apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  

  MYSQL_ROOT_PASSWORD: cm9vdA==  # "root"
  MYSQL_PASSWORD: YWRtaW4=          # "admin"    
  MYSQL_DATABASE: ZGF0YWJhc2U=      # "database"
  MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: ZmFsc2U=  # "false"
  MYSQL_RANDOM_ROOT_PASSWORD: cm9vdA==  # "root"
  MYSQL_USER: YWRtaW4=             # "admin"
 
